### ISSUE TITLE
Kubernetes symbol color is off

### ISSUE THREAD

**Issue by paddy-hack** [dcasati/kubernetes-PlantUML#4]
The Kubernetes symbols/icons in the PlantUML generated images look too light.

Just compare this icon

![K8S Pod](https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist/OSS/KubernetesPod%28m%29.svg)

with the icons in the "hello-world" example

![image](https://user-images.githubusercontent.com/6804372/86591021-b25e1d00-bfcb-11ea-8a18-2820f36362ca.png)

I've tried redefining `KUBERNETES_SYMBOL_COLOR` after including `kubernetes_Common.puml` but that doesn't fix things.  When using `#000000` the icons become grayish, so there is an effect, but they don't become black as I would have expected.

BTW, the upstream icons use `#326CE5` not `#0072C6` as defined in `dist/kubernetes_Common.puml` via `KUBERENETES_COLOR`.  FWIW, the "hello-world" uses `#66abdd` which is different again.

I suspect the C4 stuff is throwing a monkey wrench but haven't pursued that lead (yet?).

**Comment by Cerebus** [comment]
It looks to me that the problem is how plantuml is importing the original image.  When I run `java -jar plantuml.jar -encodesprite 16` on any of the source PNGs, the blue elements are mapped to a middle grey.  When plantuml applies color to sprites, it scales the color by the greyscale value, shifting the desired color.

**Comment by paddy-hack** [comment]
Actually, I did pursue my "C4 stuff" hunch and found out that led nowhere.  Sorry for not reporting that sooner.

From failing memory :wink:, I arrived at the same conclusion as @Cerebus.

**Comment by dcasati** [comment]
hey @paddy-hack, I hear you! I went through the same thing myself. Hopefully this will change in the future ...
