### ISSUE TITLE
OSS/*.puml uses AZURE_SYMBOL_COLOR instead of KUBERNETES_SYMBOL_COLOR

### ISSUE THREAD

**Issue by Cerebus** [dcasati/kubernetes-PlantUML#5]
If AZURE_SYMBOL_COLOR is undefined (e.g., another part of the stdlib is not imported) then the sprites are not visible.

If KUBERNETES_SYMBOL_COLOR is redefined, it has no effect.

**Comment by paddy-hack** [comment]
Is this still an issue now that #3 has been merged?
